// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:model2vec/model2vec.so')
library;

import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>()
external int init_embedder_advanced(
  ffi.Pointer<ffi.Char> model_path,
  ffi.Pointer<ffi.Char> hf_token,
  ffi.Pointer<ffi.Char> cache_dir,
  int normalize,
  ffi.Pointer<ffi.Char> subfolder,
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.Size,
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.Size,
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>()
external int init_embedder_from_bytes(
  ffi.Pointer<ffi.UnsignedChar> tokenizer_ptr,
  int tokenizer_len,
  ffi.Pointer<ffi.UnsignedChar> model_ptr,
  int model_len,
  ffi.Pointer<ffi.UnsignedChar> config_ptr,
  int config_len,
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>()
external int get_embedding_dimension(
  ffi.Pointer<ffi.Int> out_value,
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>()
external int get_vocabulary_size(
  ffi.Pointer<ffi.Int> out_value,
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>()
external int is_normalized(
  ffi.Pointer<ffi.Int> out_value,
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>()
external int get_median_token_length(
  ffi.Pointer<ffi.Int> out_value,
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>()
external int tokenize(
  ffi.Pointer<ffi.Char> text,
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_json,
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<ffi.Float>>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>()
external int generate_embedding(
  ffi.Pointer<ffi.Char> text,
  int max_length,
  ffi.Pointer<ffi.Pointer<ffi.Float>> out_data,
  ffi.Pointer<ffi.Size> out_dim,
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<ffi.Float>>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>()
external int generate_batch_embeddings_advanced(
  ffi.Pointer<ffi.Pointer<ffi.Char>> texts_ptr,
  int count,
  int max_length,
  int batch_size,
  ffi.Pointer<ffi.Pointer<ffi.Float>> out_data,
  ffi.Pointer<ffi.Size> out_dim,
  ffi.Pointer<ffi.Size> out_count,
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void free_string(
  ffi.Pointer<ffi.Char> s,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Float>, ffi.Size)>()
external void free_floats(
  ffi.Pointer<ffi.Float> ptr,
  int len,
);

@ffi.Native<ffi.Int Function()>()
external int is_model_loaded();

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external int free_embedder(
  ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
  )
>()
external void get_load_progress(
  ffi.Pointer<ffi.Int> out_phase,
  ffi.Pointer<ffi.Size> out_downloaded,
  ffi.Pointer<ffi.Size> out_total,
);

@ffi.Native<ffi.Void Function()>()
external void reset_load_progress();
